#Minecraft server properties
#Fri Sep 18 14:13:34 CST 2026
generator-settings=
professions=false
allow-nether=true
level-name=world
enable-query=false
server-port=25565
enable-rcon=false
force-gamemode=false
level-seed=
enable-mapping=true
server-ip=
max-build-height=256
spawn-npcs=true
spawn-animals=true
snooper-enabled=true
hardcore=false
texture-pack=
online-mode=false
difficulty=3
gamemode=0
player-idle-timeout=0
max-players=20
allow-flight-v35=true
generate-structures=true
view-distance=10
spawn-protection=16
default-map-size=4096
motd=A 1.6.4-MITE-Legend Server
